### ISSUE TITLE
Spring Data Jpa

### ISSUE THREAD

**Issue by coccocdinho** [huongdanjavacom/huongdanjava.com#2]
Bạn có thể viết 1 bài tổng quát về Spring Data Jpa được không?

**Comment by huongdanjavacom** [comment]
Xem bài viết ở đây nhé bạn https://huongdanjava.com/vi/tong-quan-ve-spring-data-jpa.html

**Comment by vuducnghia** [comment]
Mình đang đọc 1 số bài về kết hợp giữa spring boot + angular 5 nhưng đang vướng mắc ở chỗ xác thực và phân quyền. Bạn có thể viết 1 bài hoặc chỉ cho mình cách config không? 
Cảm ơn bạn nhiều

**Comment by huongdanjavacom** [comment]
Mở ticket mới đi bạn, có vẻ như bạn đang nói về Spring Security?
