### ISSUE TITLE
Java quartz scheduler

### ISSUE THREAD

**Issue by levanchien** [huongdanjavacom/huongdanjava.com#3]
Chào anh,
Anh có thể làm một bài về Quartz Scheduler trong java nói chung cũng như trong Spring được không ạ.
Cảm ơn anh.

**Comment by huongdanjavacom** [comment]
Hi bạn,

Sorry đã để bạn chờ lâu nhé!

https://huongdanjava.com/vi/gioi-thieu-ve-quartz-scheduler.html

https://huongdanjava.com/vi/su-dung-quartz-scheduler-voi-spring-framework.html

Best regards,
Khanh Nguyen
