### ISSUE TITLE
Hỏi về JPA Spring MVC

### ISSUE THREAD

**Issue by nhubang8x** [huongdanjavacom/huongdanjava.com#4]
Cho mình hỏi  làm thế nào để lấy bản ghi tiếp theo hoặc trước đó trong jpa với điều kiện biết primay key của bản ghi hiện tại cùn với một điều kiện check yêu cầu.

**Comment by huongdanjavacom** [comment]
Cụ thể hơn được không bạn ơi? Dựa vào primary key, bạn lấy được một danh sách các record trong database hay sao nhỉ?

**Comment by huongdanjavacom** [comment]
Đối với những câu hỏi, bạn có thể hỏi trên huongdanjava.com luôn bạn nhé!
