### ISSUE TITLE
Spring boot và thymeleaf: Sử dụng checkbox để chọn nhiều row trong table

### ISSUE THREAD

**Issue by hoaphongba** [huongdanjavacom/huongdanjava.com#5]
Hi, em chào anh, em mới làm quen java core và spring boot. Hiện em đang gặp 1 bài toán mà em đã tìm hiểu rất nhiều trên mạng nhưng chưa thấy cách giải nào phù hợp. Em có một table với các row and column,  mỗi row có 1 ô checkbox, bài toán đặt ra là khi tick vào ô checkbox sau đó nhấn submit thì nó chuyển sang 1 form mới chứa những row đã check. Mong a chỉ bảo, em cám ơn.!

**Comment by huongdanjavacom** [comment]
Em có thể submit thông tin của row mà em check sau đó phần controller, em redirect tới 1 trang khác với thông tin mà em đã submit. Hiểu ý anh không nhỉ?

**Comment by hoaphongba** [comment]
Hi anh, em làm được rồi ạ, em cảm ơn anh nhé.Chúc anh 1 ngày tốt lành.
